### PR TITLE
add semigroup instances

### PR DESCRIPTION
**Pull request by larskuhtz**

### CODE REVIEW

**Comment by schnecki** [comment]
You probably want to add `stimes` similarly to how `Data.Map.Strict` does it. Then the instance declaration would be:

```
instance Ord a => Monoid (MultiSet a) where
    mempty  = empty
    mconcat = unions
#if !(MIN_VERSION_base(4,9,0))
    mappend = union
#else
    mappend = (<>)

instance (Ord a) => Semigroup (MultiSet a) where
    (<>)    = union
    stimes  = stimesIdempotentMonoid
#endif
```

Once this is sorted out, please merge the pull request.

**Comment by larskuhtz** [comment]
@schnecki I added explicit implementations for `sconcat` and `stimes` to the PR

**Comment by tomjaguarpaw** [comment]
Can we please get this merged and uploaded to Hackage?

**Comment by tomjaguarpaw** [comment]
Anyone interested in doing an NMU on this?

**Pull request merged**
